apiVersion: v1
kind: Service
metadata:
  name: {{ include "vgiskill.fullname" . }}-frappe
  labels:
    {{- include "vgiskill.labels" . | nindent 4 }}
  {{- if .Values.ingress.enabled }}
  annotations:
    cloud.google.com/backend-config: '{"default": "{{ include "vgiskill.fullname" . }}-frappe-backendconfig"}'
  {{- end }}
spec:
  type: {{ .Values.frappe.service.type }}
  selector:
    app: {{ include "vgiskill.fullname" . }}-frappe
  ports:
    - name: http
      port: {{ .Values.frappe.service.port }}
      targetPort: 8000
      {{- if and (eq .Values.frappe.service.type "NodePort") .Values.frappe.service.nodePort }}
      nodePort: {{ .Values.frappe.service.nodePort }}
      {{- end }}
