apiVersion: v1
kind: Service
metadata:
  name: {{ include "vgiskill.fullname" . }}-redis
  labels:
    {{- include "vgiskill.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "vgiskill.fullname" . }}-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
